# (1) apply the coordinate classification model as agent1
# (2) When training agent1, we use SR image generated by pretrained agent2 instead of GT image
echo 'log_debug'
CUDA_VISIBLE_DEVICES=0 python3 train_spM.py --gpu 0 --dataset HistoSR  --output_name outputs/log_debug.txt
